backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads" 
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "home"
        label: "Inicio"
        file: "src/content/pages/home.json"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Imagen Principal", name: "heroImage", widget: "image" }
          - { label: "Descripción", name: "description", widget: "text" }